### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'melee' was not present in the dictionary.

### ISSUE THREAD

**Issue by CipherArrow** [maltiez2/vsmod_firearms#5]
`9.10.2023 23:29:32 [Server Debug] Block simulation loaded blocks
Game Version: v1.18.14 (Stable)
10/9/2023 11:29:34 PM: Critical error occurred
Loaded Mods:
System.Collections.Generic.KeyNotFoundException: The given key 'melee' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MaltiezFSM.Framework.FiniteStateMachine.Init(ICoreAPI api, Dictionary`2 operations, Dictionary`2 systems, Dictionary`2 i
nputs, JsonObject behaviourAttributes, CollectibleObject collectible) in D:\Projects\Firearms\fsmlib\fsmlib\src\Framework\Fini
teStateMachine.cs:line 119
   at MaltiezFSM.Framework.FiniteStateMachineBehaviour.OnLoaded(ICoreAPI api) in D:\Projects\Firearms\fsmlib\fsmlib\src\Framew
ork\FiniteStateMachineBehaviour.cs:line 38
   at Vintagestory.API.Common.CollectibleObject.OnLoaded(ICoreAPI api) in VintagestoryApi\Common\Collectible\Collectible.cs:li
ne 259
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in VintagestoryLib\Server\Systems\World\Bloc
kSimulation.cs:line 302
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 6
09
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 529
   at Vintagestory.Server.ServerProgram.Main() in VintagestoryLib\Server\ServerProgram.cs:line 123
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\C
rashReporter.cs:line 93
Crash written to file at "Logs\server-crash.txt"`

I installed the following version of your mod: maltiezfirearms_0.2.3.zip
FSMlib version: v0.1.0

The log came from my server host because the server kept going up and down up and down and their backend panel needed to be restarted so as they were 'investigating' the cause, they gave me my crash log on top of it all. The above is what it said. After removing both versions of the mod and rolling back to Firearms_0.1.11.zip, the crash stopped appearing and the server stabilized

There seems to be a problem going on between your library mod and your newer version of firearms but what it is exactly, I am uncertain which would be why I am reporting this information since you said you need more feedback/reports, and how your library file is in alpha. Hopefully this helps you out (really wanted to update but due to the crashing I couldn't).

**Comment by maltiez2** [comment]
fixed in 0.2.3, it was a problem in 0.2.2... Try 0.2.4
