### ISSUE TITLE
Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by WickedSchnitzel** [maltiez2/vsmod_firearms#6]
```
Critical error occurred
Loaded Mods: 
System.Collections.Generic.KeyNotFoundException: The given key 'melee' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MaltiezFSM.Framework.FiniteStateMachine.Init(ICoreAPI api, Dictionary`2 operations, Dictionary`2 systems, Dictionary`2 inputs, JsonObject behaviourAttributes, CollectibleObject collectible) in D:\Projects\Firearms\fsmlib\fsmlib\src\Framework\FiniteStateMachine.cs:line 119
   at MaltiezFSM.Framework.FiniteStateMachineBehaviour.OnLoaded(ICoreAPI api) in D:\Projects\Firearms\fsmlib\fsmlib\src\Framework\FiniteStateMachineBehaviour.cs:line 38
   at Vintagestory.API.Common.CollectibleObject.OnLoaded(ICoreAPI api) in VintagestoryApi\Common\Collectible\Collectible.cs:line 259
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Vintagestory.Server.ServerSystemBlockSimulation.OnBeginModsAndConfigReady() in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 302
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 609
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 529
   at Vintagestory.Server.ServerProgram.Main() in VintagestoryLib\Server\ServerProgram.cs:line 123
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by maltiez2** [comment]
Should be fixed in 0.2.3 and 0.2.4
